### PR TITLE
fixed portfolio - jekyll link

### PR DESCRIPTION
**Pull request by dnuzum**
Link to Jekyll lesson was relative path that GitBooks was not respecting. Changed to direct link. OSS FTW.

### CODE REVIEW

**Comment by bhague1281** [comment]
Approved. Thanks Derek!

**Comment by bhague1281** [comment]
@dnuzum Could you merge the latest changes?

**Comment by dnuzum** [comment]
I pulled down the changes and repushed them to my fork... Still looks like might be failing checks.

**Comment by bhague1281** [comment]
Approved

**Comment by bhague1281** [comment]
@dnuzum I think there's still an issue... you should be able to update the branch directly in Github. Let me know if there's still an issue with you merging the changes.

**Comment by dnuzum** [comment]
Got it.. I think. Didn't see the update branch button right in front of me early.

**Comment by bhague1281** [comment]
Beautiful. Thanks Derek!

**Pull request merged**
